package com.jobtracker.models.enums;

public enum StatusType {
    WISHLIST,
    INCOMPLETE,
    APPLIED,
    OA_RECEIVED,
    OA_COMPLETED,
    PHONE_SCREEN,
    TECHNICAL_INTERVIEW,
    BEHAVIORAL_INTERVIEW,
    CULTURE_FIT_INTERVIEW,
    OFFER_RECEIVED,
    OFFER_ACCEPTED,
    OFFER_DECLINED,
    REJECTED,
    WITHDRAWN
}
